stages:
  - build
  - deploy

build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build -t registry.gitlab.com/$CI_PROJECT_PATH:$CI_COMMIT_REF_SLUG .
    - docker push registry.gitlab.com/$CI_PROJECT_PATH:$CI_COMMIT_REF_SLUG
  rules:
    - if: '$CI_COMMIT_BRANCH'

deploy:
  stage: deploy
  image: docker:latest
  services:
    - docker:dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - apk add --no-cache curl
  script:
    - docker pull registry.gitlab.com/$CI_PROJECT_PATH:$CI_COMMIT_REF_SLUG
    - docker tag registry.gitlab.com/$CI_PROJECT_PATH:$CI_COMMIT_REF_SLUG render.com/$numbers:$CI_COMMIT_REF_SLUG
    - docker push render.com/$numbers:$CI_COMMIT_REF_SLUG
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
